import type { Word } from '@/types'
import { wordsData } from './words-data'

type Seed = [word: string, meaning: string, tags: string[]]

const supplementalSeeds: Seed[] = [
  ['analyze', 'v. 分析；解析', ['CET4', '高频']],
  ['approach', 'n. 方法；接近 v. 接近', ['CET4', '高频']],
  ['argument', 'n. 争论；论点；理由', ['CET4', '高频']],
  ['assume', 'v. 假设；承担；认为', ['CET4', '高频']],
  ['available', 'adj. 可获得的；有空的', ['CET4', '高频']],
  ['average', 'adj. 平均的 n. 平均数', ['CET4', '基础']],
  ['benefit', 'n. 好处；利益 v. 受益', ['CET4', '高频']],
  ['brief', 'adj. 简短的；短暂的', ['CET4', '基础']],
  ['challenge', 'n. 挑战 v. 挑战', ['CET4', '高频']],
  ['character', 'n. 性格；人物；字符', ['CET4', '高频']],
  ['combine', 'v. 结合；联合', ['CET4', '高频']],
  ['comfort', 'n. 舒适；安慰 v. 安慰', ['CET4', '基础']],
  ['comment', 'n. 评论 v. 评论', ['CET4', '基础']],
  ['community', 'n. 社区；群体', ['CET4', '高频']],
  ['compare', 'v. 比较；对照', ['CET4', '高频']],
  ['compete', 'v. 竞争；比赛', ['CET4', '高频']],
  ['complain', 'v. 抱怨；投诉', ['CET4', '基础']],
  ['complex', 'adj. 复杂的 n. 综合体', ['CET4', 'CET6']],
  ['concentrate', 'v. 集中；专心', ['CET4', '高频']],
  ['concern', 'n. 关心；担忧 v. 涉及', ['CET4', '高频']],
  ['conclusion', 'n. 结论；结束', ['CET4', '高频']],
  ['condition', 'n. 条件；状况', ['CET4', '高频']],
  ['confidence', 'n. 信心；信任', ['CET4', '高频']],
  ['confirm', 'v. 确认；证实', ['CET4', '高频']],
  ['connect', 'v. 连接；联系', ['CET4', '基础']],
  ['consider', 'v. 考虑；认为', ['CET4', '高频']],
  ['contain', 'v. 包含；容纳', ['CET4', '高频']],
  ['context', 'n. 语境；背景', ['CET4', 'CET6']],
  ['continue', 'v. 继续；延续', ['CET4', '基础']],
  ['contrast', 'n. 对比 v. 对比', ['CET4', 'CET6']],
  ['contribute', 'v. 贡献；促成；投稿', ['CET4', 'CET6']],
  ['convenient', 'adj. 方便的；便利的', ['CET4', '高频']],
  ['cooperate', 'v. 合作；配合', ['CET4', '高频']],
  ['create', 'v. 创造；创建', ['CET4', '基础']],
  ['critical', 'adj. 关键的；批判的', ['CET4', 'CET6']],
  ['culture', 'n. 文化；文明', ['CET4', '基础']],
  ['decline', 'v. 下降；拒绝 n. 衰退', ['CET4', 'CET6']],
  ['define', 'v. 定义；界定', ['CET4', '高频']],
  ['depend', 'v. 依靠；取决于', ['CET4', '高频']],
  ['describe', 'v. 描述；描写', ['CET4', '基础']],
  ['design', 'n. 设计 v. 设计', ['CET4', '高频']],
  ['detail', 'n. 细节；详情', ['CET4', '基础']],
  ['develop', 'v. 发展；培养；开发', ['CET4', '高频']],
  ['difference', 'n. 差异；不同', ['CET4', '基础']],
  ['difficult', 'adj. 困难的；艰难的', ['CET4', '基础']],
  ['direct', 'adj. 直接的 v. 指导', ['CET4', '基础']],
  ['discover', 'v. 发现；发觉', ['CET4', '高频']],
  ['discuss', 'v. 讨论；商量', ['CET4', '基础']],
  ['effective', 'adj. 有效的；生效的', ['CET4', '高频']],
  ['efficient', 'adj. 高效的；能干的', ['CET4', 'CET6']],
  ['effort', 'n. 努力；尝试', ['CET4', '高频']],
  ['encourage', 'v. 鼓励；促进', ['CET4', '高频']],
  ['environment', 'n. 环境；自然环境', ['CET4', '高频']],
  ['especially', 'adv. 尤其；特别', ['CET4', '基础']],
  ['essential', 'adj. 必不可少的；本质的', ['CET4', 'CET6']],
  ['evidence', 'n. 证据；根据', ['CET4', '高频']],
  ['excellent', 'adj. 优秀的；卓越的', ['CET4', '基础']],
  ['experience', 'n. 经验；经历 v. 经历', ['CET4', '高频']],
  ['explain', 'v. 解释；说明', ['CET4', '基础']],
  ['explore', 'v. 探索；探究', ['CET4', '高频']],
  ['express', 'v. 表达；表示', ['CET4', '基础']],
  ['factor', 'n. 因素；要素', ['CET4', '高频']],
  ['feature', 'n. 特征；特色 v. 以...为特色', ['CET4', '高频']],
  ['focus', 'n. 焦点 v. 集中', ['CET4', '高频']],
  ['foreign', 'adj. 外国的；陌生的', ['CET4', '基础']],
  ['frequent', 'adj. 频繁的；经常的', ['CET4', 'CET6']],
  ['function', 'n. 功能；作用 v. 运转', ['CET4', '高频']],
  ['general', 'adj. 一般的；总体的', ['CET4', '基础']],
  ['generate', 'v. 产生；生成', ['CET4', 'CET6']],
  ['global', 'adj. 全球的；整体的', ['CET4', '高频']],
  ['identify', 'v. 识别；确认', ['CET4', 'CET6']],
  ['imagine', 'v. 想象；设想', ['CET4', '基础']],
  ['improve', 'v. 改善；提高', ['CET4', '高频']],
  ['include', 'v. 包括；包含', ['CET4', '基础']],
  ['increase', 'v. 增加 n. 增长', ['CET4', '高频']],
  ['indicate', 'v. 表明；指示', ['CET4', 'CET6']],
  ['individual', 'adj. 个人的 n. 个人', ['CET4', '高频']],
  ['influence', 'n. 影响 v. 影响', ['CET4', '高频']],
  ['information', 'n. 信息；资料', ['CET4', '基础']],
  ['instruction', 'n. 指示；教学；说明', ['CET4', '高频']],
  ['intelligent', 'adj. 聪明的；智能的', ['CET4', '高频']],
  ['introduce', 'v. 介绍；引进', ['CET4', '基础']],
  ['involve', 'v. 涉及；包含；使参与', ['CET4', 'CET6']],
  ['knowledge', 'n. 知识；了解', ['CET4', '高频']],
  ['language', 'n. 语言；表达方式', ['CET4', '基础']],
  ['manage', 'v. 管理；设法做到', ['CET4', '高频']],
  ['method', 'n. 方法；办法', ['CET4', '高频']],
  ['necessary', 'adj. 必要的；必需的', ['CET4', '基础']],
  ['object', 'n. 物体；目标 v. 反对', ['CET4', '高频']],
  ['observe', 'v. 观察；遵守', ['CET4', 'CET6']],
  ['obtain', 'v. 获得；取得', ['CET4', 'CET6']],
  ['opinion', 'n. 意见；看法', ['CET4', '基础']],
  ['opportunity', 'n. 机会；时机', ['CET4', '高频']],
  ['organize', 'v. 组织；安排', ['CET4', '高频']],
  ['particular', 'adj. 特定的；特别的', ['CET4', '高频']],
  ['perform', 'v. 表演；执行；表现', ['CET4', '高频']],
  ['period', 'n. 时期；阶段；句号', ['CET4', '基础']],
  ['personal', 'adj. 个人的；私人的', ['CET4', '基础']],
  ['positive', 'adj. 积极的；肯定的', ['CET4', '高频']],
  ['possible', 'adj. 可能的；可行的', ['CET4', '基础']],
  ['practice', 'n. 练习；实践 v. 练习', ['CET4', '基础']],
  ['prepare', 'v. 准备；预备', ['CET4', '基础']],
  ['pressure', 'n. 压力；压强', ['CET4', '高频']],
  ['process', 'n. 过程；流程 v. 处理', ['CET4', '高频']],
  ['produce', 'v. 生产；产生', ['CET4', '高频']],
  ['project', 'n. 项目；工程 v. 投射', ['CET4', '高频']],
  ['provide', 'v. 提供；供应', ['CET4', '高频']],
  ['purpose', 'n. 目的；意图', ['CET4', '高频']],
  ['quality', 'n. 质量；品质', ['CET4', '基础']],
  ['question', 'n. 问题 v. 质疑', ['CET4', '基础']],
  ['realize', 'v. 意识到；实现', ['CET4', '高频']],
  ['reason', 'n. 原因；理由 v. 推理', ['CET4', '基础']],
  ['receive', 'v. 收到；接待', ['CET4', '基础']],
  ['recognize', 'v. 认出；承认；认可', ['CET4', '高频']],
  ['recommend', 'v. 推荐；建议', ['CET4', '高频']],
  ['record', 'n. 记录 v. 记录', ['CET4', '基础']],
  ['reduce', 'v. 减少；降低', ['CET4', '高频']],
  ['reflect', 'v. 反映；反思；反射', ['CET4', 'CET6']],
  ['relationship', 'n. 关系；联系', ['CET4', '高频']],
  ['require', 'v. 需要；要求', ['CET4', '高频']],
  ['research', 'n. 研究 v. 研究', ['CET4', '高频']],
  ['resource', 'n. 资源；资料', ['CET4', 'CET6']],
  ['respond', 'v. 回应；反应', ['CET4', '高频']],
  ['result', 'n. 结果 v. 导致', ['CET4', '基础']],
  ['review', 'n. 复习；评论 v. 复习', ['CET4', '基础']],
  ['schedule', 'n. 日程；计划 v. 安排', ['CET4', '高频']],
  ['select', 'v. 选择；挑选', ['CET4', '高频']],
  ['similar', 'adj. 相似的；类似的', ['CET4', '基础']],
  ['situation', 'n. 情况；形势', ['CET4', '基础']],
  ['specific', 'adj. 具体的；特定的', ['CET4', '高频']],
  ['standard', 'n. 标准 adj. 标准的', ['CET4', '高频']],
  ['strategy', 'n. 策略；战略', ['CET4', 'CET6']],
  ['structure', 'n. 结构；构造 v. 组织', ['CET4', '高频']],
  ['suggest', 'v. 建议；表明', ['CET4', '高频']],
  ['support', 'v. 支持 n. 支持', ['CET4', '基础']],
  ['system', 'n. 系统；体系', ['CET4', '基础']],
  ['technology', 'n. 技术；科技', ['CET4', '高频']],
  ['therefore', 'adv. 因此；所以', ['CET4', '高频']],
  ['tradition', 'n. 传统；惯例', ['CET4', '高频']],
  ['transfer', 'v. 转移；调动 n. 转移', ['CET4', 'CET6']],
  ['understand', 'v. 理解；明白', ['CET4', '基础']],
  ['valuable', 'adj. 有价值的；贵重的', ['CET4', '高频']],
  ['various', 'adj. 各种各样的', ['CET4', '高频']],
  ['volunteer', 'n. 志愿者 v. 自愿做', ['CET4', '高频']],
  ['academic', 'adj. 学术的；学院的', ['CET6', '高频']],
  ['accurately', 'adv. 准确地；精确地', ['CET6']],
  ['alternative', 'n. 替代选择 adj. 替代的', ['CET6', '高频']],
  ['ambitious', 'adj. 有雄心的；艰巨的', ['CET6']],
  ['annual', 'adj. 每年的 n. 年刊', ['CET6']],
  ['apparent', 'adj. 明显的；表面上的', ['CET6', '高频']],
  ['appropriate', 'adj. 合适的；恰当的', ['CET6', '高频']],
  ['approximately', 'adv. 大约；近似地', ['CET6']],
  ['artificial', 'adj. 人工的；虚假的', ['CET6', '高频']],
  ['assessment', 'n. 评估；评价', ['CET6', '高频']],
  ['authority', 'n. 权威；权力；当局', ['CET6']],
  ['capacity', 'n. 能力；容量', ['CET6', '高频']],
  ['category', 'n. 类别；范畴', ['CET6']],
  ['circumstance', 'n. 情况；环境', ['CET6', '高频']],
  ['civilization', 'n. 文明；文明社会', ['CET6']],
  ['commerce', 'n. 商业；贸易', ['CET6']],
  ['commitment', 'n. 承诺；投入；责任', ['CET6', '高频']],
  ['consequence', 'n. 结果；后果', ['CET6', '高频']],
  ['consistent', 'adj. 一致的；持续的', ['CET6', '高频']],
  ['constant', 'adj. 持续的；不变的', ['CET6']],
  ['consume', 'v. 消耗；消费', ['CET6', '高频']],
  ['contemporary', 'adj. 当代的；同时代的', ['CET6']],
  ['controversial', 'adj. 有争议的', ['CET6']],
  ['coordinate', 'v. 协调 n. 坐标', ['CET6']],
  ['criteria', 'n. 标准；准则', ['CET6', '高频']],
  ['demonstrate', 'v. 证明；演示；示威', ['CET6', '高频']],
  ['domestic', 'adj. 国内的；家庭的', ['CET6']],
  ['dramatic', 'adj. 戏剧性的；显著的', ['CET6']],
  ['economy', 'n. 经济；节约', ['CET6', '高频']],
  ['emphasis', 'n. 强调；重点', ['CET6']],
  ['enable', 'v. 使能够；使可能', ['CET6', '高频']],
  ['encounter', 'v. 遭遇 n. 遭遇', ['CET6']],
  ['enhance', 'v. 提高；增强', ['CET6', '高频']],
  ['estimate', 'v. 估计 n. 估计', ['CET6', '高频']],
  ['eventually', 'adv. 最终；终于', ['CET6', '高频']],
  ['evolution', 'n. 演变；进化', ['CET6']],
  ['expand', 'v. 扩大；扩展', ['CET6', '高频']],
  ['expertise', 'n. 专业知识；专长', ['CET6']],
  ['financial', 'adj. 金融的；财务的', ['CET6', '高频']],
  ['fundamental', 'adj. 基本的；根本的', ['CET6', '高频']],
  ['hypothesis', 'n. 假设；假说', ['CET6']],
  ['implement', 'v. 实施；执行 n. 工具', ['CET6', '高频']],
  ['implication', 'n. 含义；可能影响', ['CET6']],
  ['innovation', 'n. 创新；革新', ['CET6', '高频']],
  ['insight', 'n. 洞察；见解', ['CET6', '高频']],
  ['interpret', 'v. 解释；口译', ['CET6']],
  ['justify', 'v. 证明...正当；为...辩护', ['CET6']],
  ['maintain', 'v. 维持；保养；主张', ['CET6', '高频']],
  ['mechanism', 'n. 机制；机械装置', ['CET6']],
  ['migration', 'n. 迁移；移居', ['CET6']],
  ['minimum', 'n. 最小值 adj. 最小的', ['CET6']],
  ['objective', 'n. 目标 adj. 客观的', ['CET6', '高频']],
  ['potential', 'adj. 潜在的 n. 潜力', ['CET6', '高频']],
  ['prioritize', 'v. 优先处理；确定优先级', ['CET6']],
  ['proportion', 'n. 比例；部分', ['CET6']],
  ['purchase', 'v. 购买 n. 购买', ['CET6']],
  ['regulation', 'n. 规章；管理', ['CET6', '高频']],
  ['relevant', 'adj. 相关的；切题的', ['CET6', '高频']],
  ['reliable', 'adj. 可靠的；可信赖的', ['CET6', '高频']],
  ['significant', 'adj. 重要的；显著的', ['CET6', '高频']],
  ['substantial', 'adj. 大量的；实质的', ['CET6']],
  ['sufficient', 'adj. 足够的；充分的', ['CET6', '高频']],
  ['sustainable', 'adj. 可持续的', ['CET6', '高频']],
  ['technical', 'adj. 技术的；专业的', ['CET6']],
  ['ultimately', 'adv. 最终；根本上', ['CET6', '高频']],
  ['valid', 'adj. 有效的；合理的', ['CET6']],
  ['welfare', 'n. 福利；幸福', ['CET6']],
  ['coherent', 'adj. 连贯的；一致的', ['IELTS', '写作']],
  ['collocation', 'n. 搭配；词语组合', ['IELTS', '写作']],
  ['comprehensive', 'adj. 全面的；综合的', ['IELTS', '高频']],
  ['controversy', 'n. 争议；争论', ['IELTS', '写作']],
  ['dedicate', 'v. 致力于；奉献', ['IELTS']],
  ['diverse', 'adj. 多样的；不同的', ['IELTS', '高频']],
  ['emerge', 'v. 出现；浮现', ['IELTS', '高频']],
  ['evaluate', 'v. 评价；评估', ['IELTS', '写作']],
  ['facilitate', 'v. 促进；使便利', ['IELTS', '写作']],
  ['fluent', 'adj. 流利的；流畅的', ['IELTS', '口语']],
  ['highlight', 'v. 强调；突出 n. 亮点', ['IELTS', '写作']],
  ['illustrate', 'v. 说明；阐明；插图', ['IELTS', '写作']],
  ['logical', 'adj. 合乎逻辑的', ['IELTS', '写作']],
  ['perspective', 'n. 观点；视角', ['IELTS', '高频']],
  ['precise', 'adj. 精确的；准确的', ['IELTS', '写作']],
  ['pronunciation', 'n. 发音；读音', ['IELTS', '口语']],
  ['summarize', 'v. 总结；概述', ['IELTS', '写作']],
  ['transition', 'n. 过渡；转变', ['IELTS', '写作']],
]

const highFrequencyExpansion = `
account achieve activity actually addition address administration advantage advertising advise affect agency agreement allow analysis application apply arrange article aspect associate attempt attention attitude audience background balance basic behavior belief budget campaign candidate career charge choice citizen claim client colleague collection commercial communication competition concept conference conflict construction consumer contact contribution conversation corporation council customer decision demand department direction director discussion education employee employment energy engine enterprise entertainment equipment estate evaluation event examination exchange executive exercise existence expectation explanation expression extent facility failure finance foundation generation government growth guidance habit housing identity image imagination impact improvement independence industry inspection instance institution insurance interaction interest investment issue judgment leadership literature location maintenance majority management manufacturer market material measurement media membership memory message mission model movement negotiation network object obligation operation organization outcome package partnership pattern performance permission perspective philosophy policy position possibility presentation procedure production profession property proposal protection publication quantity reaction reception recognition recommendation recovery reference reflection regulation relation replacement reputation requirement resident response revenue safety satisfaction science secretary sector selection session settlement solution source statement storage strength student substance success suggestion survey system target technology tension theory training transaction transportation treatment trend university variation vehicle version welfare ability able abroad absence accept access accident accompany according accurate across action active actual adapt additional admit adult advance adventure advertise advice afford agent aggressive agriculture ahead alarm alcohol alert alien alive alternative ambition amount ancient annual anxiety apart apartment apparent appeal appearance appreciate approach appropriate approval approve argue arise arrangement arrest arrival artist assume atmosphere attach attack attractive authority available average award aware awful barrier battery battle bear beat beautiful beauty bedroom beginning benefit beside beyond birth bitter blame board borrow boundary brain branch brave breadth brief broad brother burden business capable capacity capital captain capture careful category cause celebrate central ceremony certain chain chairman challenge champion channel chapter character charity chemical chest chief childhood choice circumstance cite civil classic climate close coach coast code collapse collect college comfort comfortable command comment commitment committee common company compare comparison compete complete complex component concern conclusion concrete condition conduct confidence confirm connection conscious consequence consider constant consumer contain contemporary content context contract contribute control conventional conversation convince cooperation coordinate core corporate correct council count country courage course cousin craft crash create creature credit criteria critical crowd crucial culture curiosity current custom damage danger data debate debt decade decline decorate defend definition degree deliver demonstrate dense depend deposit describe desert design desire desk despite destroy detail detect determine develop device devote dialogue diet differ difficulty dinner direct disaster discipline discover disease dish dismiss display distance distinct divide domestic dominate drama dramatic draw dream drive economic economy edge edition educate effect effective efficiency efficient effort elder electric element eliminate emotion emphasis employ enable encounter encourage energy engage enhance enormous ensure environment equal establish estimate evidence exact examine excellent exception exchange excite executive exercise exhibit existence expand expect expensive experience experiment expert explain explore express extensive external extra factor faculty failure familiar family famous fantasy fashion feature federal feeling female figure finance financial find firm flash flexible flight focus follow force foreign forget formal former forward foundation freedom frequent friendship function fundamental future gain gap garden gather general generous global goal govern grammar gradual grant grateful guarantee guard guess guide habit handle harm harvest health height highlight history honor host household human identify ignore illustrate image immediate immigrant impact implement implication important improve incident include income increase independent indicate individual industry influence inform initial initiative innovation inquiry insight instance institute instruction instrument insurance integrate intelligence intend intense interaction interest internal interpret interview introduce invest investigation involve issue item jacket job joint judge justify knowledge label labor language latter launch lawyer leader league lecture legal legislation level liberal library license limit line link listen literal logical maintain majority manager manner market master material matter mature maximum measure media medical medium member mental message method middle migration military minimum minister minor minute mission mobile moderate modern monitor moral motion mountain movement multiple nation native nature necessary negative negotiate network normal notice notion objective observe obvious occupy occur official operate opportunity option order ordinary organize origin outcome overall package parent park particular partner passage patient pattern payment peer pension perform period permit person phase phenomenon philosophy physical planet platform pleasant pleasure policy popular population positive possess potential practical practice precise prefer prepare pressure previous primary principal principle prior priority private process produce product profession progress project promote proper property proportion propose prospect protect prove provide public purchase purpose pursue qualify quality question quick quiet range rapid rare rather reach react realistic reason receive recent recognize recommend recover reduce reflect reform refuse regard regulation reinforce reject relation relevant reliable religion remain remark remember remove repeat replace report represent request require research resident resource respond responsibility restore restrict result retain reveal revenue review revise reward rhythm risk routine safety sample satisfy scale scene schedule scheme science scope secretary section sector secure seek select senior sense sentence separate series service session settle severe shape sharp shelter shift short signal significant similar simple site situation skill sleep slight social society solution source specific stable standard statement status storage strategy strict structure struggle student subject submit substance success sufficient suggest summary supply support surface survey sustain symbol talent target technical technique tension theory therefore thought threaten throughout tradition train transfer transform transport travel treatment trend trial trouble ultimate universe valid value various version victim virtue visible volume volunteer welfare wide wisdom witness wonder`
  .trim()
  .split(/\s+/)

const expansionSeeds: Seed[] = highFrequencyExpansion.map((word) => [
  word,
  '核心高频词；释义、音标和例句由外部词典动态补全',
  ['CET4', 'CET6', '高频'],
])

const baseWordSpellings = new Set(wordsData.map((word) => word.word.toLowerCase()))

export const supplementalWords: Word[] = supplementalSeeds
  .concat(expansionSeeds)
  .filter(([word]) => !baseWordSpellings.has(word.toLowerCase()))
  .map(([word, meaning, tags], index) => ({
    id: `word-bank-${String(index + 1).padStart(4, '0')}`,
    word,
    meaning,
    phonetic: '',
    example: `Try to use "${word}" in your own English sentence today.`,
    exampleCn: `今天尝试用 ${word} 写一个自己的英文句子。`,
    chunk: undefined,
    confusingWords: [],
    tags,
  }))

export function getVocabularyBank(): Word[] {
  return [...wordsData, ...supplementalWords]
}

export function getVocabularyWordById(id: string): Word | undefined {
  return getVocabularyBank().find((word) => word.id === id)
}

export function getVocabularyByTag(tag: string): Word[] {
  return getVocabularyBank().filter((word) => word.tags.includes(tag))
}

export function searchVocabulary(query: string): Word[] {
  const lowerQuery = query.toLowerCase()
  return getVocabularyBank().filter(
    (word) => word.word.toLowerCase().includes(lowerQuery) || word.meaning.includes(query)
  )
}
